### ISSUE TITLE
Getting this error: Each LinearRing of a Polygon must have 4 or more Positions

### ISSUE THREAD

**Issue by amishas157** [mapbox/real-changesets-parser#5]
I think in this https://github.com/mapbox/real-changesets-parser/pull/4, one check was missed for calculating a closed way i.e. checking the length of the nodes. If the length of nodes[] > 2, then only a closed way can be formed. 

cc @ajithranka

**Comment by ajithranka** [comment]
Nice catch @amishas157!

**Comment by amishas157** [comment]
Making PR.

**Comment by amishas157** [comment]
Whoops sorry! commit message : (. Still can you check once? @ajithranka

**Comment by amishas157** [comment]
Thought it was merged automatically. Here is the PR: https://github.com/mapbox/real-changesets-parser/pull/6
